import './globals.css'
//import { GlobalContextProvider } from './Context/storedata'
import { PostContext, PostProvider } from './Context/PostContext'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  //   < meta http-equiv="Permissions-Policy" content = "interest-cohort=()" >
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="h-full p-3 bg-gray-900">
        <PostProvider>
          {children}
        </PostProvider>
      </body>
    </html>
  )
}
